print('===Exercicio 04===')
var = input('Digite algo: ')
print('Tipo de variavel: ',type(var))
print('E numerico? {}'.format(var.isnumeric()))
print('E caractere? {}'.format(var.isalpha()))
print('E Alfanumerico? {}'.format(var.isalnum()))
print('E decimal? {}'.format(var.isdecimal()))
print('E tudo em maisculo? {}'.format(var.isupper()))
print('E tudo em minusculo? {}'.format(var.islower()))
print('Esta capitalizado? {}'.format(var.istitle()))
print('So tem espacos? {}'.format(var.isspace()))